In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Example sentences
sentences = [
    "I love machine learning",
    "Machine learning is amazing",
    "Learning new skills is fun"
]

# Reshape the data for OneHotEncoder
sentences = np.array(sentences).reshape(-1, 1)

sentences

array([['I love machine learning'],
       ['Machine learning is amazing'],
       ['Learning new skills is fun']], dtype='<U27')

In [9]:
# Initialize OneHotEncoder

# Parameters Explained
# handle_unknown='ignore': Ensures that unseen labels during encoding won't raise an error.
# sparse=False: Converts the result to a dense numpy array (default is a sparse matrix).
# get_feature_names_out(): Retrieves the names of the one-hot encoded features.
    
    
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the data
one_hot_encoded = encoder.fit_transform(sentences)

In [10]:
# Feature names (column names after encoding)
features = encoder.get_feature_names_out(['Sentences'])

# Display results
print("One-Hot Encoded Matrix:\n", one_hot_encoded)
print("\nFeature Names:\n", features)


One-Hot Encoded Matrix:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

Feature Names:
 ['Sentences_I love machine learning'
 'Sentences_Learning new skills is fun'
 'Sentences_Machine learning is amazing']
