In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Example sentences
sentences = [
    "money gets money",
    "people earn money",
    "money make money"
]

# Reshape the data for OneHotEncoder
sentences = np.array(sentences).reshape(-1, 1)

sentences

array([['money gets money'],
       ['people earn money'],
       ['money make money']], dtype='<U17')

In [13]:
# Initialize OneHotEncoder

# Parameters Explained
# handle_unknown='ignore': Ensures that unseen labels during encoding won't raise an error.
# sparse=False: Converts the result to a dense numpy array (default is a sparse matrix).
# get_feature_names_out(): Retrieves the names of the one-hot encoded features.
    
# Key Difference:
# Dense = All values stored.
# Sparse = Only non-zero values stored.
    
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit and transform the data
one_hot_encoded = encoder.fit_transform(sentences)

In [14]:
# Feature names (column names after encoding)
features = encoder.get_feature_names_out(['Sentences'])

# Display results
print("One-Hot Encoded Matrix:\n", one_hot_encoded)
print("\nFeature Names:\n", features)


One-Hot Encoded Matrix:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

Feature Names:
 ['Sentences_money gets money' 'Sentences_money make money'
 'Sentences_people earn money']
